(function() {var implementors = {};
implementors["base64"] = [{"text":"impl Error for <a class=\"enum\" href=\"base64/enum.DecodeError.html\" title=\"enum base64::DecodeError\">DecodeError</a>","synthetic":false,"types":["base64::decode::DecodeError"]}];
implementors["embedded_svc"] = [{"text":"impl&lt;R, W&gt; Error for <a class=\"enum\" href=\"embedded_svc/io/enum.CopyError.html\" title=\"enum embedded_svc::io::CopyError\">CopyError</a>&lt;R, W&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;R: Display + Debug,<br>&nbsp;&nbsp;&nbsp;&nbsp;W: Display + Debug,&nbsp;</span>","synthetic":false,"types":["embedded_svc::io::CopyError"]}];
implementors["esp_idf_hal"] = [{"text":"impl Error for <a class=\"struct\" href=\"esp_idf_hal/can/struct.CanError.html\" title=\"struct esp_idf_hal::can::CanError\">CanError</a>","synthetic":false,"types":["esp_idf_hal::can::CanError"]},{"text":"impl Error for <a class=\"struct\" href=\"esp_idf_hal/can/struct.Can02Error.html\" title=\"struct esp_idf_hal::can::Can02Error\">Can02Error</a>","synthetic":false,"types":["esp_idf_hal::can::Can02Error"]},{"text":"impl Error for <a class=\"struct\" href=\"esp_idf_hal/i2c/struct.I2cError.html\" title=\"struct esp_idf_hal::i2c::I2cError\">I2cError</a>","synthetic":false,"types":["esp_idf_hal::i2c::I2cError"]},{"text":"impl Error for <a class=\"struct\" href=\"esp_idf_hal/serial/struct.SerialError.html\" title=\"struct esp_idf_hal::serial::SerialError\">SerialError</a>","synthetic":false,"types":["esp_idf_hal::serial::SerialError"]},{"text":"impl Error for <a class=\"struct\" href=\"esp_idf_hal/spi/struct.SpiError.html\" title=\"struct esp_idf_hal::spi::SpiError\">SpiError</a>","synthetic":false,"types":["esp_idf_hal::spi::SpiError"]}];
implementors["esp_idf_sys"] = [{"text":"impl Error for <a class=\"struct\" href=\"esp_idf_sys/struct.EspError.html\" title=\"struct esp_idf_sys::EspError\">EspError</a>","synthetic":false,"types":["esp_idf_sys::error::EspError"]}];
implementors["log"] = [{"text":"impl Error for <a class=\"struct\" href=\"log/struct.SetLoggerError.html\" title=\"struct log::SetLoggerError\">SetLoggerError</a>","synthetic":false,"types":["log::SetLoggerError"]},{"text":"impl Error for <a class=\"struct\" href=\"log/struct.ParseLevelError.html\" title=\"struct log::ParseLevelError\">ParseLevelError</a>","synthetic":false,"types":["log::ParseLevelError"]}];
implementors["num_enum"] = [{"text":"impl&lt;Enum:&nbsp;<a class=\"trait\" href=\"num_enum/trait.TryFromPrimitive.html\" title=\"trait num_enum::TryFromPrimitive\">TryFromPrimitive</a>&gt; Error for <a class=\"struct\" href=\"num_enum/struct.TryFromPrimitiveError.html\" title=\"struct num_enum::TryFromPrimitiveError\">TryFromPrimitiveError</a>&lt;Enum&gt;","synthetic":false,"types":["num_enum::TryFromPrimitiveError"]}];
implementors["serde"] = [{"text":"impl Error for <a class=\"struct\" href=\"serde/de/value/struct.Error.html\" title=\"struct serde::de::value::Error\">Error</a>","synthetic":false,"types":["serde::de::value::Error"]}];
implementors["serde_json"] = [{"text":"impl Error for <a class=\"struct\" href=\"serde_json/struct.Error.html\" title=\"struct serde_json::Error\">Error</a>","synthetic":false,"types":["serde_json::error::Error"]}];
implementors["strum"] = [{"text":"impl Error for <a class=\"enum\" href=\"strum/enum.ParseError.html\" title=\"enum strum::ParseError\">ParseError</a>","synthetic":false,"types":["strum::ParseError"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()